### ISSUE TITLE
Construção dos Indicadores

### ISSUE THREAD

**Issue by RobsonOL** [RobsonOL/avaliacao_secties#2]
## Roadmap

- [ ] Unir bases de discentes, bolsistas, teses e produção acadêmica.
- [ ] Filtrar para modalidades Mestrado e Doutorado.
- [ ] Criar três grupos de comparação: bolsistas Fapesq, bolsistas não-Fapesq e não bolsitas. 

Construir os indicadores:

- [ ] Número de bolsistas
- [ ] Taxa de titulação
- [ ] Tempo médio das bolsas
- [ ] Tempo médio de conclusão
- [ ] Estratificação por gênero e idade
- [ ] Em relação à produção acadêmica
- [ ] Proporção de artigos acadêmicos por Qualis
- [ ] Proporção de artigos acadêmicos por quartil
